source 'http://rubygems.org'

gem 'rails', '~> 3.0.20'
gem 'rake'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2', '~> 0.2.18'


# Bundle the extra gems:

gem 'pony', '1.3'
gem 'rmagick', '2.13.2', :require => 'RMagick'
gem 'pdf-reader'
gem 'money'
gem 'active_shipping'
gem 'activemerchant', '~> 1.20.0'
gem 'will_paginate', '~> 3.0.0'
gem 'meta_where'
gem 'sanitize'
gem 'thinking-sphinx'
gem 'acts_as_tree_rails3'
gem 'dynamic_form'
gem 'fastercsv'
gem "paperclip", "2.7.0"
gem "cocaine", "0.2.1"
gem 'uuidtools'
gem 'wrest'

# Deployment and monitoring gems
gem 'capistrano'
gem 'capistrano-ext'
gem 'airbrake'
gem 'newrelic_rpm'


# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'debugger'
  gem 'rspec-rails'
  # To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
  #gem 'ruby-debug'
  #gem 'ruby-debug19', :require => 'ruby-debug'
end

group :test do
  gem 'factory_girl', '~> 2.2'
  gem 'factory_girl_rails'
  gem 'simplecov'
  gem 'cucumber-rails'
  gem 'capybara-webkit'
  gem 'database_cleaner' # For clearing the database after cucumber runs.
  gem 'launchy'
  gem 'email_spec'
  gem 'ruby-prof', "0.8.1"
  gem 'pickle'
  gem 'test-unit', '1.2.3'
end
